'О нас' and 'Условия использования и лицензии' views added, the first…
AksanaKarpenka/CalculatorTask pull request #2
Opened 2017-05-28 11:50 UTC by AksanaKarpenka

… one is opened in stack and the last one is opened as modal

2017-05-29 10:38 UTC, imironenko requested changes

2017-05-29 10:38 UTC, imironenko commented on LicenseViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *closeUIButton;
В чем надобность создание этого оутлета ?

2017-05-29 10:38 UTC, imironenko commented on AKCalculator/ViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *licenseInfoUIButton;
В чем надобность создание этого оутлета ?

2017-06-05 19:44 UTC, imironenko requested changes

2017-06-05 19:44 UTC, imironenko commented on AKCalculator/ViewController.m
> +    UIBarButtonItem *aboutUsUIBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"О нас"
memory leak

2017-06-20 20:10 UTC, imironenko requested changes

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/ViewController.h
> +    BOOL isTypingNumber;
давай использовать свойства

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/ViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *sqrtUIButton;
зачем нам оутлеты на все кнопки с операциями ?

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/ViewController.m
> +        if (self.model.operationCount == 2) {
не прозрачное решение для операций с двумя операндами, по мне `operationCount` возвращает кол-во возможных операций, давай подумаем как от этого уйти

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/ViewController.m
> +- (IBAction)changeSignTapped:(id)sender {
Давай сделаем, чтобы наша модель выплняла данную операцию

2017-06-20 20:10 UTC, imironenko commented on CalculatorNotificationController.h
> +@interface CalculatorNotificationController : NSObject
для чего нам этот контроллер? он не несет смысловой нагрузки, делегировать результат должна моделька и уведомлять контроллер об изменениях вычисления

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/CalculatorModel.m
> +- (CGFloat)performOperation:(CGFloat)operand {
Стоит сделать более корректное наименование `performOperationWithOperand:` такое наименование предполагает, что аргумент у нас операция

2017-06-20 20:10 UTC, imironenko commented on AKCalculator/CalculatorModel.h
> +@interface CalculatorModel : UIViewController
Почему моделька наследуется от UIViewController ?

2017-07-16 21:24 UTC, AksanaKarpenka commented on AKCalculator/ViewController.m
> +    UIBarButtonItem *aboutUsUIBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"О нас"
Исправлено

2017-07-16 21:25 UTC, AksanaKarpenka commented on AKCalculator/ViewController.h
> +    BOOL isTypingNumber;
Свойства добавлены

2017-07-16 21:25 UTC, AksanaKarpenka commented on AKCalculator/ViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *sqrtUIButton;
Лишние оутлеты удалены

2017-07-16 21:26 UTC, AksanaKarpenka commented on AKCalculator/ViewController.m
> +        if (self.model.operationCount == 2) {
Переделано с использованием констант

2017-07-16 21:33 UTC, AksanaKarpenka commented on AKCalculator/ViewController.m
> +- (IBAction)changeSignTapped:(id)sender {
Логика перемещена в модель

2017-07-16 21:33 UTC, AksanaKarpenka commented on CalculatorNotificationController.h
> +@interface CalculatorNotificationController : NSObject
Удален

2017-07-16 21:33 UTC, AksanaKarpenka commented on AKCalculator/CalculatorModel.m
> +- (CGFloat)performOperation:(CGFloat)operand {
Метод переименован

2017-07-16 21:43 UTC, AksanaKarpenka commented on AKCalculator/CalculatorModel.h
> +@interface CalculatorModel : UIViewController
Исправлено на NSObject. Видимо, при создании новых файлов стояло UIViewController.

2017-07-16 21:44 UTC, AksanaKarpenka commented on AKCalculator/ViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *licenseInfoUIButton;
Удален

2017-07-16 21:44 UTC, AksanaKarpenka commented on LicenseViewController.h
> +@property (retain, nonatomic) IBOutlet UIButton *closeUIButton;
Удален

2017-08-07 12:30 UTC, imironenko approved these changes
👍

2017-08-07 14:00 UTC, merged