Added constraint and ability to move operations button
AksanaKarpenka/CalculatorTask pull request #3
Opened 2017-06-18 16:31 UTC by AksanaKarpenka

2017-06-20 20:13 UTC, imironenko requested changes
Расположение кнопок, должно изменяться при повороте экрана

2017-07-23 16:02 UTC, AksanaKarpenka commented
Исправлено: группа кнопок меняет расположение при повороте экрана

2017-08-08 21:13 UTC, imironenko commented
Убери, пожалуйста конфликты

2017-08-09 20:26 UTC, AksanaKarpenka commented
Конфликты резолвнуты

2017-08-10 08:53 UTC, imironenko approved these changes
👍

2017-08-10 10:21 UTC, merged